baseURL = 'https://byuantl.github.io/'
languageCode = 'en-us'
title = 'Bowen Yuan'
theme = ["hugo-embed-pdf-shortcode", "hugo-book"]

enableInlineShortcodes = true

enableEmoji = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

copyright = '[Â© CC BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode)'

# Needed for mermaid/katex shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.tableOfContents]
  startLevel = 1

disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
    BookTheme = 'auto'
    BookSection = '*'
    BookPortableLinks = 'warning'
    BookFavicon = 'B.png'